# Generated by Django 5.2.3 on 2025-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
