# Generated by Django 5.2.3 on 2025-06-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
    ]
