# Generated by Django 5.2.3 on 2025-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_media_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.TextField(max_length=120)),
                ('img', models.URLField(null=True)),
            ],
        ),
    ]
