# Generated by Django 5.2.3 on 2025-06-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.AlterField(
            model_name='about',
            name='para',
            field=models.TextField(),
        ),
    ]
