# Generated by Django 5.2.3 on 2025-06-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_about_img_alter_about_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(default='exit', unique=True),
            preserve_default=False,
        ),
    ]
