# Generated by Django 5.2.3 on 2025-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_media_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
