# Generated by Django 5.2.3 on 2025-06-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_media_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='slug',
        ),
    ]
