# Generated by Django 5.2.3 on 2025-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_media_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
