# Generated by Django 5.2.3 on 2025-07-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_media_content_alter_media_img_alter_media_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
