# Generated by Django 5.2.3 on 2025-07-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_media_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='slug',
        ),
    ]
