# Generated by Django 5.2.3 on 2025-07-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='categer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
    ]
