# Generated by Django 5.2.4 on 2025-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_media_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='about',
            name='para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/images'),
        ),
    ]
