# Generated by Django 5.2.4 on 2025-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_media_is_publish_alter_about_para_alter_media_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
