# Generated by Django 5.2.4 on 2025-07-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_media_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='img_url',
        ),
    ]
