# Generated by Django 5.2.4 on 2025-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_media_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
